# -*- coding: utf-8 -*-  

alphabet_upper_mapper_letter_to_class = {
    'A': 'upper_a',
    'B': 'upper_b',
    'C': 'upper_c',
    'Č': 'upper_c1',
    'Ć': 'upper_c2',
    'D': 'upper_d',
    'Đ': 'upper_d1',
    'E': 'upper_e',
    'F': 'upper_f',
    'G': 'upper_g',
    'H': 'upper_h',
    'I': 'upper_i',
    'J': 'upper_j',
    'K': 'upper_k',
    'L': 'upper_l',
    'M': 'upper_m',
    'N': 'upper_n',
    'O': 'upper_o',
    'P': 'upper_p',
    'R': 'upper_r',
    'S': 'upper_s',
    'Š': 'upper_s1',
    'T': 'upper_t',
    'U': 'upper_u',
    'V': 'upper_v',
    'Z': 'upper_z',
    'Ž': 'upper_z1',
    'X': 'upper_x',
    'Y': 'upper_y',
    'W': 'upper_w',
    'Q': 'upper_q',
}

alphabet_lower_mapper_letter_to_class = {
    'a': 'lower_a',
    'b': 'lower_b',
    'c': 'lower_c',
    'č': 'lower_c1',
    'ć': 'lower_c2',
    'd': 'lower_d',
    'đ': 'lower_d1',
    'e': 'lower_e',
    'f': 'lower_f',
    'g': 'lower_g',
    'h': 'lower_h',
    'i': 'lower_i',
    'j': 'lower_j',
    'k': 'lower_k',
    'l': 'lower_l',
    'm': 'lower_m',
    'n': 'lower_n',
    'o': 'lower_o',
    'p': 'lower_p',
    'r': 'lower_r',
    's': 'lower_s',
    'š': 'lower_s1',
    't': 'lower_t',
    'u': 'lower_u',
    'v': 'lower_v',
    'z': 'lower_z',
    'ž': 'lower_z1',
    'x': 'lower_x',
    'y': 'lower_y',
    'w': 'lower_w',
    'q': 'lower_q',
}

number_letter_to_class = {
    '0': 'number_0',
    '1': 'number_1',
    '2': 'number_2',
    '3': 'number_3',
    '4': 'number_4',
    '5': 'number_5',
    '6': 'number_6',
    '7': 'number_7',
    '8': 'number_8',
    '9': 'number_9',
}

special_letter_to_class = {
    '.': 'special_dot',
    ',': 'special_comma',
    '?': 'special_question',
    '!': 'special_exclamation',
    '-': 'special_minus',
    '(': 'special_left_bracket',
    ')': 'special_right_bracket'
}

vocab_letter_to_class = {
    **alphabet_lower_mapper_letter_to_class,
    **alphabet_upper_mapper_letter_to_class,
    **number_letter_to_class,
    **special_letter_to_class
}